apiVersion: v1
kind: Pod                  # 创建的资源类型 pod
metadata:
  name: ember-app          # 资源名称
  labels:
    app: ember-app                                  
spec:                                                
  containers:
    - image: nginx:k8s    # 镜像名称                            
      name: ember-app     # pod container 的名称            
      ports:
        - containerPort: 80   # 容器监控 port