apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - image: zhyq0826/python:k8s-python-app
          imagePullPolicy: Always
          name: python-app
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local